name: Get full info

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: metadata-full-info-${{ github.repository }}
  queue: max

jobs:
  generate:
    uses: sergey-symbiotic/metadata-validation-scripts/.github/workflows/full-info.yml@5db4ac5ff5e4171b01ace750c9ee46ebae351f42
    with:
      implementation-ref: 5db4ac5ff5e4171b01ace750c9ee46ebae351f42
