name: Get full info

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: metadata-full-info-${{ github.repository }}
  queue: max

jobs:
  generate:
    uses: sergey-symbiotic/metadata-validation-scripts/.github/workflows/full-info.yml@2b6213f5c6b1562c09d82f80f3e8fa2ef5c5153f
    with:
      implementation-ref: 2b6213f5c6b1562c09d82f80f3e8fa2ef5c5153f
