name: Get full info

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read

concurrency:
  group: metadata-full-info-${{ github.repository }}
  queue: max

jobs:
  generate:
    uses: sergey-symbiotic/metadata-validation-scripts/.github/workflows/full-info.yml@ea2fdd1af83732f83fb2100c93eea8de5dadbeeb
    with:
      implementation-ref: ea2fdd1af83732f83fb2100c93eea8de5dadbeeb
